#Client to Server messages
CONNECT = "CONNECT"
PLAYER_INPUT = "PLAYER_INPUT"
DISCONNECT = "DISCONNECT"

#Server to Client messages
SERVER_DISCONNECTED = "SERVER_DISCONNECTED"
MATCH_FOUND = "MATCH_FOUND"
GAME_STATE = "GAME_STATE"
MATCH_CLOSED = "MATCH_CLOSED"
ERROR = "ERROR"