# Client -> Server
CONNECT = "CONNECT"
PLAYER_INPUT = "PLAYER_INPUT"
RESPAWN = "RESPAWN"
SPLIT = "SPLIT"
EJECT = "EJECT"

# Shared
DISCONNECT = "DISCONNECT"

# Server -> Client
MATCH_FOUND = "MATCH_FOUND"
GAME_STATE = "GAME_STATE"
PLAYER_DEAD = "PLAYER_DEAD"
ERROR = "ERROR"

CLIENT_EVENT_MESSAGES = {
    MATCH_FOUND,
    DISCONNECT,
    ERROR,
    PLAYER_DEAD,
}