
CONNECTION_ERROR_BACKGROUND_COLOR = (30, 30, 30)

CONNECTION_ERROR_TITLE = "Connection Error"
CONNECTION_ERROR_TITLE_COLOR = (255, 80, 80)
CONNECTION_ERROR_TITLE_Y = 180

CONNECTION_ERROR_DEFAULT_MESSAGE = "El servidor no está disponible. Por favor, intentá reconectarte más tarde."

CONNECTION_ERROR_MESSAGE_COLOR = (220, 220, 220)
CONNECTION_ERROR_MESSAGE_Y = 250

CONNECTION_ERROR_TITLE_FONT_SIZE = 56
CONNECTION_ERROR_MESSAGE_FONT_SIZE = 32

CONNECTION_ERROR_BACK_BUTTON_WIDTH = 200
CONNECTION_ERROR_BACK_BUTTON_HEIGHT = 60
CONNECTION_ERROR_BACK_BUTTON_Y = 360

CONNECTION_ERROR_BACK_BUTTON_TEXT = "Back"

CONNECTION_ERROR_BACK_BUTTON_BACKGROUND_COLOR = (80, 160, 255)
CONNECTION_ERROR_BACK_BUTTON_HOVER_COLOR = (100, 180, 255)