LEADERBOARD_TITLE = "Leaderboard"

LEADERBOARD_WIDTH = 220
LEADERBOARD_HEIGHT = 180

LEADERBOARD_MARGIN_TOP = 20
LEADERBOARD_MARGIN_RIGHT = 20

LEADERBOARD_TITLE_OFFSET_X = 15
LEADERBOARD_TITLE_OFFSET_Y = 10

LEADERBOARD_ENTRY_OFFSET_X = 15
LEADERBOARD_ENTRY_OFFSET_Y = 45

LEADERBOARD_LINE_HEIGHT = 26
LEADERBOARD_MAX_PLAYERS = 5

LEADERBOARD_BACKGROUND_COLOR = (45, 45, 45)
LEADERBOARD_BACKGROUND_ALPHA = 160

LEADERBOARD_TEXT_COLOR = (255, 255, 255)
LEADERBOARD_LOCAL_PLAYER_COLOR = (255, 120, 120)
