MATCHMAKING_FONT_SIZE = 48

MATCHMAKING_CANCEL_BUTTON_TEXT = "Cancel"

MATCHMAKING_CANCEL_BUTTON_Y = 350

MATCHMAKING_CANCEL_BUTTON_WIDTH = 200
MATCHMAKING_CANCEL_BUTTON_HEIGHT = 60

MATCHMAKING_CANCEL_BUTTON_COLOR = (200, 70, 70)
MATCHMAKING_CANCEL_BUTTON_HOVER_COLOR = (230, 90, 90)

MATCHMAKING_BACKGROUND_COLOR = (25, 25, 25)

MATCHMAKING_TEXT = "Buscando partida..."
MATCHMAKING_TEXT_COLOR = (255, 255, 255)

MATCHMAKING_TEXT_Y = 220