PLAYING_BACKGROUND_COLOR = (230, 230, 230)

PLAYING_SCORE_FONT_SIZE = 32
PLAYING_LEADERBOARD_FONT_SIZE = 26
PLAYING_USERNAME_FONT_SIZE = 16

PLAYING_PLAYER_BORDER_DARKEN_AMOUNT = 40
PLAYING_PLAYER_INNER_RADIUS_OFFSET = 3

PLAYING_SCORE_TEXT_COLOR = (40, 40, 40)
PLAYING_SCORE_MARGIN_LEFT = 20
PLAYING_SCORE_MARGIN_BOTTOM = 40

PLAYING_USERNAME_TEXT_COLOR = (255, 255, 255)

PLAYING_VIRUS_SPIKE_COUNT = 12
PLAYING_VIRUS_SPIKE_LENGTH = 8

ENTITY_PLAYER = "player"
ENTITY_VIRUS = "virus"
