PLAYING_BACKGROUND_COLOR = (230, 230, 230)

PLAYING_SCORE_FONT_SIZE = 32
PLAYING_LEADERBOARD_FONT_SIZE = 26
PLAYING_USERNAME_FONT_SIZE = 16

PLAYER_BORDER_DARKEN_AMOUNT = 40
PLAYER_INNER_RADIUS_OFFSET = 3

SCORE_TEXT = "Score"
SCORE_TEXT_COLOR = (40, 40, 40)

SCORE_MARGIN_LEFT = 20
SCORE_MARGIN_BOTTOM = 20

LEADERBOARD_TITLE = "Leaderboard"

LEADERBOARD_WIDTH = 220
LEADERBOARD_HEIGHT = 180

LEADERBOARD_MARGIN_TOP = 20
LEADERBOARD_MARGIN_RIGHT = 20

LEADERBOARD_TITLE_OFFSET_X = 15
LEADERBOARD_TITLE_OFFSET_Y = 10

LEADERBOARD_ENTRY_OFFSET_X = 15
LEADERBOARD_ENTRY_OFFSET_Y = 45

LEADERBOARD_LINE_HEIGHT = 26
LEADERBOARD_MAX_PLAYERS = 5

LEADERBOARD_BACKGROUND_COLOR = (45, 45, 45)
LEADERBOARD_BACKGROUND_ALPHA = 160

LEADERBOARD_TEXT_COLOR = (255, 255, 255)
LEADERBOARD_LOCAL_PLAYER_COLOR = (255, 120, 120)

USERNAME_TEXT_COLOR = (255, 255, 255)

DEFAULT_USERNAME = "Player"