RESPAWN_STATE_PANEL_WIDTH = 500
RESPAWN_STATE_PANEL_HEIGHT = 360

RESPAWN_STATE_PANEL_Y = 50
RESPAWN_STATE_PANEL_COLOR = (235, 235, 235)

RESPAWN_STATE_OVERLAY_ALPHA = 120
RESPAWN_STATE_OVERLAY_COLOR = (0,0,0)

RESPAWN_STATE_TITLE = "Match Results"

RESPAWN_STATE_TITLE_FONT_SIZE = 52
RESPAWN_STATE_TEXT_FONT_SIZE = 34

RESPAWN_STATE_TITLE_COLOR = (30, 30, 30)
RESPAWN_STATE_TEXT_COLOR = (40, 40, 40)
RESPAWN_STATE_VALUE_COLOR = (20, 20, 20)

RESPAWN_STATE_TITLE_OFFSET_Y = 45

RESPAWN_STATE_STATS_START_Y = 105
RESPAWN_STATE_STATS_LINE_SPACING = 75

RESPAWN_STATE_LEFT_COLUMN_X = 120
RESPAWN_STATE_RIGHT_COLUMN_X = 370

RESPAWN_STATE_VALUE_OFFSET_Y = 28

RESPAWN_STATE_PANEL_BORDER_RADIUS = 12

RESPAWN_STATE_RESPAWN_BUTTON_TEXT = "Respawn"
RESPAWN_STATE_BACK_BUTTON_TEXT = "Back"

RESPAWN_STATE_BUTTON_WIDTH = 220
RESPAWN_STATE_BUTTON_HEIGHT = 60

RESPAWN_STATE_RESPAWN_BUTTON_Y = 440
RESPAWN_STATE_BACK_BUTTON_Y = 515

RESPAWN_STATE_BUTTON_OFFSET_X = 110

RESPAWN_STATE_RESPAWN_BUTTON_COLOR = (70, 170, 90)
RESPAWN_STATE_RESPAWN_BUTTON_HOVER_COLOR = (90, 200, 110)

RESPAWN_STATE_BACK_BUTTON_COLOR = (180, 70, 70)
RESPAWN_STATE_BACK_BUTTON_HOVER_COLOR = (210, 90, 90)

RESPAWN_STATE_FOOD_EATEN_LABEL = "food eaten"
RESPAWN_STATE_TIME_ALIVE_LABEL = "time alive"
RESPAWN_STATE_CELLS_EATEN_LABEL = "cells eaten"
RESPAWN_STATE_HIGHEST_MASS_LABEL = "highest mass"
RESPAWN_STATE_LEADERBOARD_TIME_LABEL = "leaderboard time"
RESPAWN_STATE_TOP_POSITION_LABEL = "top position"



