# server/config/__init__.py
from .match_config import MATCH_TICK_RATE, TOP_PLAYERS_LEADERBOARD, PLAYER_EAT_MASS_MULTIPLIER
from .player_config import (
    PLAYER_INITIAL_MASS, ATTEMPS_TO_SPAWN,
    PLAYER_MAX_SPEED, PLAYER_MIN_SPEED, PLAYER_SPEED_FACTOR,
    SPLIT_MIN_MASS, SPLIT_MAX_CELLS, SPLIT_EJECT_SPEED, SPLIT_EJECT_FRICTION, SPLIT_MERGE_TIMER,
    CELL_MAX_ATTRACTION,
    EJECT_MIN_MASS, EJECT_MASS_AMOUNT, EJECT_FOOD_RADIUS, EJECT_SPEED, EJECT_FRICTION,
)
from .food_config import FOOD_INITIAL_AMOUNT, FOOD_TYPES
from .virus_config import VIRUS_INITIAL_AMOUNT, VIRUS_MAX_AMOUNT, VIRUS_INITIAL_MASS, VIRUS_SPLIT_MASS, VIRUS_EJECT_SPEED, VIRUS_COLOR, VIRUS_SPAWN_ATTEMPTS, VIRUS_SAFE_DISTANCE
from .colors import ENTITIES_COLORS