from .colors import DARK_GREEN

VIRUS_INITIAL_AMOUNT = 10
VIRUS_MAX_AMOUNT = 20
VIRUS_INITIAL_MASS = 100
VIRUS_SPLIT_MASS = 160
VIRUS_EJECT_SPEED = 700
VIRUS_COLOR = DARK_GREEN

VIRUS_SPAWN_ATTEMPTS = 30
VIRUS_SAFE_DISTANCE = 200
